# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptions',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_description', to='course_app.Courses'),
        ),
    ]
