# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('course_app', '0002_auto_20170321_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(related_name='course_users', to='log_reg.Users'),
        ),
    ]
